listener 1883
listener 9001
protocol websockets
allow_anonymous true
max_connections 500
max_queued_messages 10000
log_type error
log_type warning
log_type notice
persistence true
persistence_location /mosquitto/data/
